/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "slice_constants.h"

namespace Slice {

const sliceConstants g_slice_constants;

sliceConstants::sliceConstants() {
}

} // namespace

