/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef slice_CONSTANTS_H
#define slice_CONSTANTS_H

#include "slice_types.h"

namespace Slice {

class sliceConstants {
 public:
  sliceConstants();

};

extern const sliceConstants g_slice_constants;

} // namespace

#endif
