/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ExtractFile */

#ifndef _Included_ExtractFile
#define _Included_ExtractFile
#ifdef __cplusplus
extern "C" {
#endif
#define JavaFunc(name) Java_com_platform_util_ExtractFile_##name
/*
 * Class:     ExtractFile
 * Method:    CreateMDSFile
 * Signature: (Ljava/lang/String;)V
 */
	JNIEXPORT void JNICALL JavaFunc(CreateMDSFile)
  (JNIEnv *, jobject, jstring);

/*
 * Class:     ExtractFile
 * Method:    GetTileData
 * Signature: (III)[B
 */
JNIEXPORT jbyteArray JNICALL JavaFunc(GetTileData)
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     ExtractFile
 * Method:    ReleaseMDSFile
 * Signature: ()V
 */
JNIEXPORT void JNICALL JavaFunc(ReleaseMDSFile)
  (JNIEnv *, jobject);

/*
 *  * Class:     ExtractFile
 *   * Method:    GetThumbnail
 *    * Signature: ()V
 *     */

JNIEXPORT jbyteArray JNICALL JavaFunc(GetThumbnail)
	  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
